local s = require("soundmod")

local function t(text)
for i = 1, #text do
local ch=  text:sub(i,i)
io.write(ch)
io.flush()
local delay = math.random() * 0.1
os.execute("sleep " .. delay)
end
end

local function sleep()
    os.execute("sleep 1.75")
end

local function adddot()
    io.write(".")
    io.flush()
end

local function emph()
    os.execute("sleep 0.1")
end

local function centeredprint(text)
	local handle = io.popen("tput cols")
	local cols = tonumber(handle:read("*a")) or 80
	handle:close()
	local padding = math.floor((cols - #text) / 2)
	if padding < 0 then padding = 0 end
	print(string.rep(" ", padding) .. text)
end

local function asdf()
    s.antag(1)
    print("Hello!")
    os.execute("sleep 1")
    s.antag(1)
    print("What is your name?")
    
    local name = io.read()
    s.player(1)
    sleep()
    if name == "John" then
        print("Oh! That's my name too!")
	s.antag(1)
        os.execute("sleep 1")
        print("We have the same name!")
        s.antag(1)
        sleep()
    elseif name == "Alice" then
        print("Oh! What a coincidence!")
        s.antag(1)
        sleep()
        print("That's my wife's name!")
	s.antag(1)
	sleep()
    elseif
        name == "" then
        print("Give me your name or else")
	s.gs(1)
	os.execute("feh images/force.jpg")
        asdf()
    end
    sleep()
    print("You have a cool name!")
    s.antag(1)
    os.execute("sleep 1")
    s.antag(1)
    print("Anyway, How are you today? (good,bad,mid)")
    s.antag(1)
    local feelings = io.read()
    if feelings == "good" then
        print("Me too! :3")
        s.antag(1)
        os.execute("sleep 1")
        print("I am also feeling good today!")
        s.antag(1)
    elseif feelings == "bad" then
        print("I am sorry for you!")
	s.antag(2)
        os.execute("sleep 2")
        print("Talk to me and you can feel better! :3")
	s.antag(1)
    elseif feelings == "mid" then
        print("yea this day feels mid ngl")
	s.antag(2)
        os.execute("sleep 2")
        print("But we can make this day happy!")
	s.antag(1)
    else
        print("sry right now i can only respond to: good, bad, mid")
	s.antag(1)
        os.execute("sleep 1")
        print("But my creator will add more responses!")
	s.antag(1)
        os.exit()
    end
    sleep()
    print("Let's have some fun! It is very boring in this terminal...")
    s.antag(1)
    os.execute("sleep 1")
    print("What are some things you like? (you are forced to say 'anything')")
    s.antag(1)
    local hobby = io.read()
    if hobby == "anything" or hobby == "Anything" or hobby == "ANYTHING" then
        s.player(1)
        sleep()
        print("Hooray!!")
        s.antag(1)
        sleep()
        print("Let's do random fun things!")
        s.antag(1)
        sleep()
        print("Like uhm")
        s.antag(1)
        sleep()
        io.write(".")
        adddot()
        adddot()
        sleep()
        adddot()
        adddot()
        os.execute("sleep 0.1")
        adddot()
        adddot()
        os.execute("sleep 0.1")
        adddot()
        print("I know!!")
	s.antag(1)
        sleep()
        print("I have thought of a game!!!")
        s.antag(1)
        sleep()
        print("It's called")
        s.antag(1)
        sleep()
        s.antag(3)
        for j = 1,100 do
            adddot()
            print("\n")
        end
        print("MM'````'YMM MM````````MM MM`````````M MMP```````MM M````````M MM`````````M")
        emph()
        print("M' .mmm. `M MM  mmmm,  M MM  mmmmmmmM M' .mmmm  MM Mmmm  mmmM MM  mmmmmmmM ")
        emph()
        print("M  MMMMMooM M'        .M M`      MMMM M         `M MMMM  MMMM MM      MMMM ")
        emph()
        print("M  MMMMMMMM MM  MMMb. 'M MM  MMMMMMMM M  MMMMM  MM MMMM  MMMM MM  MMMMMMMM ")
        emph()
        print("M. `MMM' .M MM  MMMMM  M MM  MMMMMMMM M  MMMMM  MM MMMM  MMMM MM  MMMMMMMM ")
        emph()
        print("MM.     .dM MM  MMMMM  M MM        .M M  MMMMM  MM MMMM  MMMM MM        .M ")
        emph()
        print("MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMM MMMMMMMMMMMM ")
        emph()
        emph()
        emph()
        print("                  ")
        emph()
        print(".d8888b. 88d888b. ")
        emph()
        print("88'  `88 88'  `88 ")
        emph()
        print("88.  .88 88       ")
        emph()
        print("`88888P' dP       ")
        emph()
        print("                  ")
    else
        print("Oh well.. Goodbye!")
        os.exit()
    end
    sleep()
    print("(say 'or what??')")
    local orwhat = io.read()
    if orwhat == "or what??" or orwhat == "Or what?" or orwhat == "or what" then
        s.player(1)
        sleep()
        emph()
        print("You might have said 'or what'")
        s.antag(1)
        adddot()
        emph()
        adddot()
        emph()
        adddot()
        sleep()
        print("BUT YOU ARE WRONG!!!!")
        s.antag(2)
        sleep()
        sleep()
        print("You: but how is a question wrong????")
        s.player(1)
        sleep()
        print("ALSO WRONG!!!")
        s.antag(1)
        sleep()
        print("We are doing something no game has ever done before!!!")
        s.antag(2)
        sleep()
        sleep()
        s.antag(4)
        print("MM'````'YMM MM````````MM MM`````````M MMP```````MM M````````M MM`````````M")
        emph()
        print("M' .mmm. `M MM  mmmm,  M MM  mmmmmmmM M' .mmmm  MM Mmmm  mmmM MM  mmmmmmmM ")
        emph()
        print("M  MMMMMooM M'        .M M`      MMMM M         `M MMMM  MMMM MM      MMMM ")
        emph()
        print("M  MMMMMMMM MM  MMMb. 'M MM  MMMMMMMM M  MMMMM  MM MMMM  MMMM MM  MMMMMMMM ")
        emph()
        print("M. `MMM' .M MM  MMMMM  M MM  MMMMMMMM M  MMMMM  MM MMMM  MMMM MM  MMMMMMMM ")
        emph()
        print("MM.     .dM MM  MMMMM  M MM        .M M  MMMMM  MM MMMM  MMMM MM        .M ")
        emph()
        print("MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMM MMMMMMMMMMMM ")
        emph()
        print("                  ")
        emph()
        print(".d8888b. 88d888b. ")
        emph()
        print("88'  `88 88'  `88 ")
        emph()
        print("88.  .88 88       ")
        emph()
        print("`88888P' dP       ")
        emph()
        print("                  ")
        emph()
        print([[      _    _   ___   _______ _   _ ___ _   _  ____   ]])
        emph()
        print([[     / \  | \ | \ \ / /_   _| | | |_ _| \ | |/ ___|  ]])
        emph()
        print([[    / _ \ |  \| |\ V /  | | | |_| || ||  \| | |  _   ]])
        emph()
        print([[   / ___ \| |\  | | |   | | |  _  || || |\  | |_| |  ]])
        emph()
        print([[ //_/   \_\_| \_| |_|   |_| |_| |_|___|_| \_|\____|\ ]])
        emph()
        print([[/___________________________________________________\]])
        sleep()
        emph()
        emph()
        print("WHAT DO YOU THINK???(u can respond with anything)")
	s.antag(1)
        io.read()
        print("Well I didn't hear you, sorry!")
        s.antag(1)
        sleep()
        print("Anyway, let's play!!!")
	s.antag(1)
        sleep()
        emph()
        print("you: what's the rules of the game")
	s.player(1)
        sleep()
        print("Oh i forgot!!")
	s.antag(1)
        sleep()
        print("Yes! The rules!!")
        s.antag(1)
        sleep()
        print("ok.. so are them:")
        s.antag(1)
        sleep()
	s.antag(2)
	print("1. You can NOT save your game")
        emph()
        print("2. Every time you fail, a random bad thing happens!!!")
        emph()
        print("3. The levels get more goofy!!!")
        emph()
        print("4. Each level is only one try")
	emph()
        print("5. Think carefully")
        emph()
        print("6. Find cool secrets!!")
        emph()
        sleep()
        sleep()
        print("That's all the rules for now!! OK LET'S PLAY")
        s.antag(1)
        sleep()
        sleep()
        os.execute("clear")
	string.rep("\n", 10)
	centeredprint("HELLO!!!!! LOADING THE GAME..")
	centeredprint("[")
        local right = { yes = true }
	for i = 1, 200 do
		os.execute("sleep 0.03")
		io.write("#")
		io.flush()
	end
	io.write("]")
	return right
    else
        local right = { yes = false }
        print("(you have misspelled the phrase. QUITTING THE GAME!!!)")
        s.player(2)
        sleep()
        print("(tip: always double check what you type)")
        sleep()
        return right
    end
end

return asdf()
